PWD = $(shell pwd)
NVIDIA_SDK_INSTALL_PATH ?= /usr/local/cuda
ATISTREAMSDKROOT ?= /usr/local/ati

TARGET = clfft_example.exe

CXXFLAGS += -O3 -Wall -g -I$(NVIDIA_SDK_INSTALL_PATH)/OpenCL/common/inc -I$(ATISTREAMSDKROOT)/include -I../include -D_WIN32_WINDOWS=0x0410 -malign-double
LDFLAGS += $(PWD)/../lib/libclfft.a ../lib/amd/win32/2.3/OpenCL.lib

$(TARGET): main.cpp Makefile $(PWD)/../lib/libclfft.a
	i586-mingw32msvc-g++ $(CXXFLAGS) main.cpp $(LDFLAGS) -o $(TARGET)

clean:
	rm -f $(TARGET)
